### ISSUE TITLE
Use github pages?

### ISSUE THREAD

**Issue by CodeBrauer** [anushbmx/CSS-Cursors#11]
[Github provides serving html pages with this repository.](https://pages.github.com/)

You never know the url provided will be up to date and available everywhere, github is - and this for free - why not use it? - You can also add an own domain to github pages

**Comment by anushbmx** [comment]
I didn't get what you meant by URL provided will be up to date and available everywhere .?

@CodeBrauer I created this for self-reference on my blog as I do normally never thought it would take a big hit.

**Comment by CodeBrauer** [comment]
W
